# Generated by Django 6.0.2 on 2026-03-07 05:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('GRAM', 'Gram'), ('LITER', 'Liter'), ('PIECE', 'Piece'), ('DOZEN', 'Dozen'), ('QUINTAL', 'Quintal'), ('SACK', 'Sack')], default='KG', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('category', models.CharField(choices=[('VEGETABLES', 'Vegetables'), ('FRUITS', 'Fruits'), ('GRAINS', 'Grains'), ('SPICES', 'Spices'), ('DAIRY', ' Dairy'), ('MEAT', ' Meat'), ('LEGUMES', 'Legumes/Pulses'), ('OILSEEDS', 'Oilseeds'), ('OTHERS', 'Others')], default='VEGETABLES', max_length=50)),
                ('district', models.CharField(blank=True, help_text='Location where product is available', max_length=50, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
